x-common-env-vars: &common-env-vars
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://postgres:postgres@postgres:5432
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql://postgres:postgres@postgres:5432
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__FERNET_KEY: "d6Vefz3G9U_ynXB3cr7y_Ak35tAHkEGAVxuz_B-jzWw="
  AIRFLOW__WEBSERVER__SECRET_KEY: "dae-rl-2-project_6ace21"
  AIRFLOW__WEBSERVER__RBAC: "True"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  ASTRONOMER_ENVIRONMENT: local

networks:
  airflow:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  airflow_logs:
    driver: local

services:
  postgres:
    image: docker.io/postgres:12.6
    restart: unless-stopped
    networks:
      - airflow
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
    ports:
      - 127.0.0.1:5432:5432
    volumes:      
      - postgres_data:/var/lib/postgresql/data
      
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  scheduler:
    image: dae-rl-2-project_6ace21/airflow:latest
    command: >
      bash -c "(airflow db upgrade || airflow upgradedb) && airflow scheduler"
    restart: unless-stopped
    networks:
      - airflow
    user: astro
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
      io.astronomer.docker.component: "airflow-scheduler"
    depends_on:
      - postgres
    environment: *common-env-vars
    volumes:
      - /home/airc/dae_rl2_project/dags:/usr/local/airflow/dags:z
      - /home/airc/dae_rl2_project/plugins:/usr/local/airflow/plugins:z
      - /home/airc/dae_rl2_project/include:/usr/local/airflow/include:z
      - /home/airc/dae_rl2_project/tests:/usr/local/airflow/tests:z
      - /home/airc/dae_rl2_project/airflow_settings.yaml:/usr/local/airflow/airflow_settings.yaml:z   
      - airflow_logs:/usr/local/airflow/logs
      
    

  webserver:
    image: dae-rl-2-project_6ace21/airflow:latest
    command: >
      bash -c 'if [[ -z "$$AIRFLOW__API__AUTH_BACKEND" ]] && [[ $$(pip show -f apache-airflow | grep basic_auth.py) ]];
        then export AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.basic_auth ;
        else export AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.default ; fi &&
        { airflow users create "$$@" || airflow create_user "$$@" ; } &&
        { airflow sync-perm || airflow sync_perm ;} &&
        airflow webserver' -- -r Admin -u admin -e admin@example.com -f admin -l user -p admin
    restart: unless-stopped
    networks:
      - airflow
    user: astro
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
      io.astronomer.docker.component: "airflow-webserver"
    depends_on:
      - scheduler
      - postgres
    environment: *common-env-vars
    ports:
      - 127.0.0.1:20003:8080
    volumes:
      - /home/airc/dae_rl2_project/dags:/usr/local/airflow/dags:z
      - /home/airc/dae_rl2_project/plugins:/usr/local/airflow/plugins:z
      - /home/airc/dae_rl2_project/include:/usr/local/airflow/include:z
      - /home/airc/dae_rl2_project/tests:/usr/local/airflow/tests:z      
      - airflow_logs:/usr/local/airflow/logs       

  triggerer:
    image: dae-rl-2-project_6ace21/airflow:latest
    command: >
      bash -c "(airflow db upgrade || airflow upgradedb) && airflow triggerer"
    restart: unless-stopped
    networks:
      - airflow
    user: astro
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
      io.astronomer.docker.component: "airflow-triggerer"
    depends_on:
      - postgres
    environment: *common-env-vars
    volumes:
      - /home/airc/dae_rl2_project/dags:/usr/local/airflow/dags:z
      - /home/airc/dae_rl2_project/plugins:/usr/local/airflow/plugins:z
      - /home/airc/dae_rl2_project/include:/usr/local/airflow/include:z      
      - airflow_logs:/usr/local/airflow/logs
      
    

